### ISSUE TITLE
Deployment stability

### ISSUE THREAD

**Issue by Br3nda** [ServiceInnovationLab/FSD#107]
- [x] dev/prod settings needed
- [x] Deploys to github need to use production settings, not local dev
- [x] deploy from circle-ci needs to work reliably

**Comment by mischa-s** [comment]
Unpacking 6am brain:

## What I think happened:

- repo name changed
- automatic build failed
- noticed outdated string `/fsd-spike` in script tag
- rebuilt locally with local `.env` with correct `REACT_APP_GH_PAGES_SUFFIX=/FSD`
- manual deployed
- fixed npm build problem
- auto deploys still failing attributed to gh-pages
- Manually fixed gh-pages problem with [this suggestions](https://discuss.circleci.com/t/no-config-found-builds-marked-as-failed/24912)
- Shiny tried locally using old `.env
- Shiny re-tried using new `.env (worked?)
- Later on I was in circle-ci settings and noticed `env` variables still had old `/fsd-spike` suffix
- Updated to new suffix
- Auto-deploy is back happening :tada:, circle-ci still insisting on trying to build gh-pages branch :disappointed: 

## confusing factors
- repo rename
- switch commands from yarn to npm omit of build
- circle-ci failing on gh-pages branch creating noise
- circle-ci managing own `env`

**Comment by mischa-s** [comment]
If this is accurate
* [x] dev/prod settings needed - we have circle-ci env, just need to remember to use

* [x]  Deploys to github need to use production settings, not local dev - again, circle-ci covers this

* [x]  deploy from circle-ci needs to work reliably - as long as we keep its env up to date it should work, the gh- pages question aside

**Comment by Br3nda** [comment]
Re-opening. The site isn't deploying. I get a  github 404 page after every circle ci deploy

**Comment by Br3nda** [comment]
Added @lamorrison after discussing on slack
