### ISSUE TITLE
Referral info  missing and cost duplicated

### ISSUE THREAD

**Issue by choirboy07** [ServiceInnovationLab/FSD#131]
In the Services Detail the information on costs is showing twice and there is no information on referrals.

**Comment by sarahneeson** [comment]
Appearance in Searchinator
![snippet.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a2613c599d956001145c2b3/125516c66e82c728ace21e0d46fb9a93339286bdcda5fd53b652fa912a5265296b51a07a28d6e170bc4478545d5718ac415e0d17fcf08179a7a42062c80d55b98e30063e937f03a6aa8317b500bf258b4f87b7bb8f4ac7e83537aa.png)

Appearance in FSD
![snippet 2.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a2613c599d956001145c2b3/125516c66e82c728ace21e0d46fb9a93339286bdcfbbfd0fe64de29b234324676b5ee17e73d4bb7bbd1a78070c5a4ca417585f42aeaa8922aee43d62964e49bc8f3900299f7744eeaa880dbe06b0218e4a85b6be8b44c6e03f2ce099c2.PNG)
