### ISSUE TITLE
HIGH PRIORITY: Search initiation

### ISSUE THREAD

**Issue by choirboy07** [ServiceInnovationLab/FSD#161]
When using the "Enter topic or organisation" (ETO) field the results presented vary dependent on the search initiation sequence.

Scenario:

I enter Addiction in the ETO field then start typing my address and select from the list.  

Expected result:I would expect to get providers delivering addiction related services near my address.

Actual result: I get providers near my address.

Reason:  Entering a keyword in ETO does not initiate a search, whereas selecting a topic or address do.  So if I don't hit search after entering the keyword then my search string is not updated.

Possible solution(s): make any action post entering a keyword include the keyword in the search string; or

Change the order of searching on the home page so that ETO is the 3rd action and has Search immediately below it.

*Acceptance Criteria*
- [x] Initialise search

**Comment by choirboy07** [comment]
![Search Addiction as keyword.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c61fc6e865e1b0011e12374/125516c66e82c728ace21e0d46db919b31818be9aeedbb4aa749f99b27062660690fa632678af12cfd0e39111d0014f9121c4d4eeefcda2aaeb56e78d90a58e8d3650974c63b43ffb88b17ed00a83c990dd4e8e8d51199a26867f5819d4e3914041d8cff5a34a79f4fcb51f743f300.JPG)
![Typed  Addiction then Select Address.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c61fc6e865e1b0011e12374/125516c66e82c728ace21e0d46dc8d8a2686c3e9aeedbb4aa749f99b2706337b2c0ae3187589e62bab025a050b1d1bef024a4356bcbbd671f3e57862804e0ebed0655c26ce6e47ffbd8017e901ba26d91c85bfb4d84dd2f42f67b6d5db1063474f4dcbed5727a19e41c95df34be64c52a21a3262e47e2431.JPG)
![Click on Search for Addiction and Address.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c61fc6e865e1b0011e12374/125516c66e82c728ace21e0d46cb98932089c3a681a98c46a54ff39c694028616925a72f7986f721b04c3b00010b5edd150c1d11bfba9b37b4f67e2fd00958a9c3674d71953c19afea8a4ce952bf22831985b6bad81fc0e13577e699935d7c4f5b4cd6a2047ff5db59c24af743eb4c50a1133162e171367c409d196761.JPG)

**Comment by choirboy07** [comment]
Shows the sequence of my test

**Comment by dlouise64** [comment]
Added Acceptance Criteria

**Comment by dlouise64** [comment]
closes #175

**Comment by sarahneeson** [comment]
Resolutions for this card captured in card #190
(which was subsequently broken down to individual tickets #192, #193, #195, #196, #198)

Fixes to include:
- Radius becomes action buttons (makes them dynamic)
- Add in a magnifying glass next to text input (replaces "Search" button)
- Show Map goes down (appears in search results area, simplifies search initiation area)
- Reset search keep it in its current state
 
This card can be closed
