### ISSUE TITLE
HIGH PRIORITY: Duplicate results when searching by keyword and address

### ISSUE THREAD

**Issue by sarahneeson** [ServiceInnovationLab/FSD#162]
***Scenario***
Given I am on the Find Whanau Support site
When I search using a keyword and an address
Then I should see a single result for each provider that matches the search criteria (within agreed limits)

***Example***
Enter topic or organisation: Addiction
Start typing address: 1 Viewmont Drive, Harbour View, Lower Hutt 5010

***Expected result in above search***
<=10 individual results featuring the keyword addiction within close proximity to 1 Viewmont Drive, Harbour View.
(Note, after change to # of results limitation, we would expect <=50 results)

***Actual result in above search***
9 out of the 10 results displayed are for the same organisation: “Mental Health and Addiction Services – Hutt Valley DHB”.   (Provider ID in dataset = 5854).

**Comment by sarahneeson** [comment]
[Duplicate results when searching by keyword and address.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a2613c599d956001145c2b3/125516c66e82c728ace21e0d46cc818a2f8b80a89becff51a14ee5983d5567642101ad6b6380e23abc4a720f084f1ce551030a0dbba6cb7fb6e762249a0d5fb993381c37d42103ecfadd45ea52fe32815d80e5bd824f92e06e73b48e8d47681e051edbac5d3ca8cb4ada44e409b01301fb4e6f29b33424765595197f2d6e6226acfdd85f828568a4bf0262.docx)

**Comment by choirboy07** [comment]
Note: the duplication is still present but reduced if a topic is also selected e.g. Select Addiction, type topic = Addiction and then select Address as above and now only 2 listings of same organisation in 10 results.

**Comment by dlouise64** [comment]
closes #176

**Comment by Br3nda** [comment]
@JacOng17 @dlouise64 is this ready to be tested?

**Comment by Br3nda** [comment]
@dlouise64 is this done? CAn you retest?

**Comment by sarahneeson** [comment]
Have re-tested the above scenarios, and am not seeing any duplication at all.  Same applies for other searches including keywords.

I also tested just selecting a category, example Legal / Civil Services.  Results for that included a large number of Citizens Advice Bureaux, but confirmed no duplication (see below).

I think this is fixed.

Citizens Advice Bureau - Avondale	
Citizens Advice Bureau - Birkenhead	
Citizens Advice Bureau - Browns Bay	
Citizens Advice Bureau - Buller	
Citizens Advice Bureau - Central Auckland	
Citizens Advice Bureau - Central Wellington	
Citizens Advice Bureau - Christchurch North	
Citizens Advice Bureau - Eastern Suburbs Wellington	
Citizens Advice Bureau - Eden / Albert at St Lukes	
Citizens Advice Bureau - Glen Innes	
Citizens Advice Bureau - Hastings	
Citizens Advice Bureau - Hauraki	
Citizens Advice Bureau - Hawera	
Citizens Advice Bureau - Johnsonville	
Citizens Advice Bureau - Kapiti	
Citizens Advice Bureau - Levin	
Citizens Advice Bureau - Lower Hutt	
Citizens Advice Bureau - Marlborough	
Citizens Advice Bureau - Massey	
Citizens Advice Bureau - Mt Roskill	
Citizens Advice Bureau - Napier	
Citizens Advice Bureau - New Plymouth	
Citizens Advice Bureau - Newtown	
Citizens Advice Bureau - North Otago	
Citizens Advice Bureau - Northcote	
Citizens Advice Bureau - Otaki	
Citizens Advice Bureau - Pakuranga-Eastern Manukau	
Citizens Advice Bureau - Palmerston North	
Citizens Advice Bureau - Papakura	
Citizens Advice Bureau - Queenstown	
Citizens Advice Bureau - Rotorua	
Citizens Advice Bureau - Sylvia Park	
Citizens Advice Bureau - Takapuna	
Citizens Advice Bureau - Taupo	
Citizens Advice Bureau - Upper Hutt	
Citizens Advice Bureau - Wairarapa Inc	
Citizens Advice Bureau - Wellington West	
Citizens Advice Bureau - Whakatane	
Citizens Advice Bureau - Whanganui	
Citizens Advice Bureau Christchurch Area - Christchurch West	
Citizens Advice Bureau Christchurch Area - The Loft	
Citizens Advice Bureau Invercargill Inc.	
Citizens Advice Bureau Mangere	
Citizens Advice Bureau Nelson Tasman	
Citizens Advice Bureau Otara Incorporated	
Citizens Advice Bureau Porirua	
Citizens Advice Bureau South Canterbury Inc	
Department of Internal Affairs	
Taranaki Community Law Trust

**Comment by sarahneeson** [comment]
@choirboy07 Note this is now closed and in the Accepted list :)
