### ISSUE TITLE
Empty Category of Doom

### ISSUE THREAD

**Issue by sarahneeson** [ServiceInnovationLab/FSD#169]
25/2/19 <s>a green box</s> an empty category button has appeared to the left of the category/topic buttons.

Affects both mobile and desktop.

<s>Doesn't appear to have a function, but is distracting. </s>
EDIT: Paul has discovered that the empty category affects the search results in a negative way.  See comment below for detail.

See screen grabs.

![Screenshot_20190225-114605.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a2613c599d956001145c2b3/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cd791475266455f27f26d5b66af3006b1300051bff054a5556f9aa8823a5e43423dc0f0eefd93b5f74c06f42acb18a4dbe13a632c91edbe2e3d7158abd7f37ed998d4f341f001d88ff5832a19f42c05df659ac.jpg)

![Interesting green box.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a2613c599d956001145c2b3/125516c66e82c728ace21e0d46c19a8e269086ba9be0b144e45ae2912c486771261ce1673295f127b54778154d555ca912595747aef1da7df5b33e78dc5c0beb833e5f7dce6f10bea4905dee5fee7fd616cfe3fe9846d2e93a2fe68e8a4e3e1b021981f85d35a28b06.PNG)

**Comment by sarahneeson** [comment]
**Impact of the Empty Category of Doom**

1. Start typing and select an address
*Example: 56 The Terrace, Wellington Central, Wellington 6011*

2. Note the first result
_Example_

![search by address.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a2613c599d956001145c2b3/125516c66e82c728ace21e0d46fb919b31818be98df0ff42a059e2913a55653f6b14b1247a80e03cfd1839540c5e46af13500c12affc8b23f0b63c76d80f0be4d93f5e66da2f53fde6d640e258f075c95d8fa4bd8246c1ed3824e78d8a493d19061d81ed10.PNG)

3. Scroll up and select a category/topic
_Example: Building Financial Capability_

![choosing a category.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a2613c599d956001145c2b3/125516c66e82c728ace21e0d46eb9c952c918aa788a9be03a75ce4912e49356a6b48e13b628ae92dbc56395b4d5a1dad495b0d4cafafda2ea4be6a708a5a59bed1645726c72f0dbefad341eb5ee779c11ac7a4b6984dc8e23c20e28a8f493b1702118cf85b27ed.PNG)

4. Note what the first result is now that you've added a category/topic
_Example_

![search by address and topic.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a2613c599d956001145c2b3/125516c66e82c728ace21e0d46fb919b31818be98df0ff42a059e2913a5567722700e33f7f95ea2bfd0e39111d0014f9121c4d4eeefcda2aaeb56e78d90a58e8d3650974c63b43ffb88b17ed00a83c990dd4e8e8d51199a26867f5819d4d3e14041d8cfe5d33a59e4fcb59f449f300.PNG)

5. Scroll up and select the Empty Category of Doom

[Link to the search results after selecting the Empty Category of Doom](https://serviceinnovationlab.github.io/FSD/#/FSD/?address=56%20The%20Terrace%2C%20Wellington%20Central%2C%20Wellington%206011&latitude=-41.280816&longitude=174.774872l)

Result: 
The search summary remains the same, it still states both the address and category/topic.
However, the results themselves have changed as if the category/topic was removed:

![after the green box of doom.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a2613c599d956001145c2b3/125516c66e82c728ace21e0d46e9928e2690c3bd87ecff44b658f59a6944286b690ba56b748aec25fd0e39111d0014f9121c4d4eeefcda2aaeb56e78d90a58e8d3650974c63b43ffb88b17ed00a83c990dd4e8e8d51199a26867f5819d4e3914041d8cfe5d33a5914ecb5af243f300.PNG)

**Comment by JacOng17** [comment]
We found out that it was because of the top row where the "LEVEL_1_CATEGORY" was blank hence it was interpreted as a valid category (although it didn't have any text/value):
![Empty Category.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bbfc42dd4762b0011a329b7/125516c66e82c728ace21e0d46cd998a379bc38a8efdba44ab4fe9d665043761260ea62864c7b96aea412a595c0d46ff170b5a46f4af892ba0e46f70835459ecc3714d36976345f3e5db55ea43a82a994d84bcbd8f49c1e83b23e08989473c1b1755.png)

**Comment by choirboy07** [comment]
The guilty data item is still in the database (and extract) however there is no longer an empty category/topic box.

Boom - well down.
