### ISSUE TITLE
Initialise search when min 2 letters are entered

### ISSUE THREAD

**Issue by dlouise64** [ServiceInnovationLab/FSD#181]
A/C

 - [ ] Search is initialised when min of 2 letters are entered into the topic field

**Comment by JacOng17** [comment]
![iphoneX.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bbfc42dd4762b0011a329b7/125516c66e82c728ace21e0d46e184922c8c8691cda5fd53b652fa912a5265296b51a07a28d6e170bc4478545d5718ac415e0d17fcf08179a7a42062c80d55b98e30063e937f03a6aa8317b500bf25894d83b6b48244c2e03537aa.png)
Seems like the text would be too long to fit into the screen.

**Comment by dlouise64** [comment]
@JacOng17 I will update the ticket, a better approach will be to initialise the search after 2 letters have been entered as discussed last week with the devs.

**Comment by choirboy07** [comment]
If searching is going to be dynamic after the entry of 2 characters then can we remove the "Search" button and just have a Re-set Search that clears everything?  How will the dynamic search work if someone copy/pastes into the box?  If we need to keep the search button to initiate this then maybe the "instruction text" could be "type keyword(s) and hit Search".

**Comment by Br3nda** [comment]
closing. We use the search button
