### ISSUE TITLE
Move distance (km) filter to the results section

### ISSUE THREAD

**Issue by sarahneeson** [ServiceInnovationLab/FSD#182]
_Given I am on the Find Whanau Support site_
_When I start typing an address_
_Then the Distance (km) filter only appears once I have selected an address to search with (and it appears in the results area)._

![Move distance filter to the results area.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a2613c599d956001145c2b3/125516c66e82c728ace21e0d46c59b8c26c287a09cfdbe4da758b092204a33763b44b7243091eb2dff507e121a030aef51091d11adeb9539e6f4632adf0f4fffdb7f5a27c73512feb0d149ec04b828dd4f85b0eed94cc9e06f24f5979d0d6f405147d4a61760e28b41da59fe41e04850a6103263e476377c42960c38.PNG)

**Comment by choirboy07** [comment]
Hi, the filter needs to be dynamic on selection - this was the case but the latest version is that the results are not changing when you change the distance unless you then click on Search.
