### ISSUE TITLE
Replace search button with magnifying glass

### ISSUE THREAD

**Issue by lamorrison** [ServiceInnovationLab/FSD#192]
Replace the existing search button with a little magnifying glass button beside the keyword search box

Acceptance Criteria
- [ ] There is a magnifying glass button beside the keyword search box
- [ ] The existing search button is removed

**Comment by CharlotteHinton** [comment]
@sarahneeson @choirboy07 ready for you to review

**Comment by choirboy07** [comment]
@sarahneeson Magnifying glass is there and selecting it invokes a search. PASSED
