### ISSUE TITLE
Change radius selector to be buttons

### ISSUE THREAD

**Issue by lamorrison** [ServiceInnovationLab/FSD#193]
The radius selector, which is currently a radio button group, should be styled as buttons so that users will understand that when they change the search radius it will perform an action (updating the search results).

Also, the form behaviour should be updated so that a search is triggered when the radius is changed

Acceptance Criteria
- [ ] The radius selector is styled as buttons
- [ ] When the radius selection is changed a search is triggered

**Comment by CharlotteHinton** [comment]
@sarahneeson @choirboy07 ready for you to review

**Comment by choirboy07** [comment]
Theses are now buttons and when a different one is tapped (selected) the results are updated.
