### ISSUE TITLE
Test Accessibility

### ISSUE THREAD

**Issue by lamorrison** [ServiceInnovationLab/FSD#195]
Consider Lighthouse in Chrome, do a quick screen reader test. 
Run lighthouse & listen to a screen reader.

TODO: Lyall will check with Ackama for other accessibility best practices

**Comment by JacOng17** [comment]
Not interested in PWAs.

**Comment by JacOng17** [comment]
[Uploading Accessibility.png...]
![Buttons.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bbfc42dd4762b0011a329b7/125516c66e82c728ace21e0d46ca818e378d8dbacda5fd53b652fa912a5265296b51a07a28d6e170bc4478545d5718ac415e0d17fcf08179a7a42062c80d55b98e30063e937f03a6aa8317b500bf25884d84beb9884cc7e03f37aa.png)
[Uploading Colour Contrast.png...]
[Uploading No associated labels.png...]

**Comment by JacOng17** [comment]
Have added a label to the Address searchbox for accessibility. Will need to have a quick chat on this.

**Comment by CharlotteHinton** [comment]
@choirboy07 @sarahneeson nothing for you to test on this one - FYI
