### ISSUE TITLE
Show result count

### ISSUE THREAD

**Issue by lamorrison** [ServiceInnovationLab/FSD#196]

**Comment by lamorrison** [comment]
Show the number of results after a search is performed (at the top of the results list?)

Acceptance Criteria
- [] The number of results is visible after a search is performed

**Comment by CharlotteHinton** [comment]
@sarahneeson @choirboy07 ready for you to review

**Comment by choirboy07** [comment]
@sarahneeson results count is displaying in summary search line above list of results and is there if you select Show on map - passed.
