### ISSUE TITLE
Search summary does not capture location

### ISSUE THREAD

**Issue by sarahneeson** [ServiceInnovationLab/FSD#200]
The search summary captures all search criteria, except selected location.

Example: 
https://serviceinnovationlab.github.io/FSD/#/FSD/?latitude=-38.66137&longitude=178.019055&region=Gisborne

![Screenshot Gisborne selected.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a2613c599d956001145c2b3/125516c66e82c728ace21e0d46db978826878dba87e6ab038354e396265429766917a6277586f72dbb0037431f1d11f6140b1b56f6eb8c78a7be3f22820f5dbed46f5722c63d17feeb8216b753bb32975dc7e7e2de139db17770a599855d3f170f198cfa5f3da79042ce5df54ee45f18.PNG)

**Comment by sarahneeson** [comment]
I think a user would expect to see the search summary reflect their selected location.
This is especially so when using a combination of criteria, 
eg. Search on "oscar" keyword, and location "Gisborne"

Search summary currently only reflects the keyword:
![search summary only shows keyword.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a2613c599d956001145c2b3/125516c66e82c728ace21e0d46fb919b31818be99cfcb24ea54fe9d426482b6a6917ab246796a323ba5b6c0e1d0b5cb053181d1ba6acda6fb4bc2e75d95d03ee83650c22953813a4ee821fb953e9208247d7b7ae965e82b96371b8d6d6056b5c17129bfe5a3fa19c4eca50fe4be5485da0173071ab.PNG)

Even though the URL clearly shows that the region "Gisborne" has been captured in the search:
"Gisborne"https://serviceinnovationlab.github.io/FSD/#/FSD/?keyword=oscar&latitude=-38.66137&longitude=178.019055&radius=25&region=Gisborne

**Comment by sarahneeson** [comment]
@choirboy07 - let me know if I've missed anything with this specific ticket

**Comment by CharlotteHinton** [comment]
@sarahneeson @choirboy07 ready for you to test this.

**Comment by choirboy07** [comment]
@sarahneeson @CharlotteHinton  Hi, this is now working as expected with location showing in the search summary.
