### ISSUE TITLE
Stand Children's Services (Auckland) not found

### ISSUE THREAD

**Issue by lamorrison** [ServiceInnovationLab/FSD#216]
Split from #185

Searching for the keywords "Stand Children's Services" does not return a result for a known service provider with that name in Auckland. Other related service providers around the country are found.

Search for the keywords "Stand Children's Services auckland" finds the expected service provider

**Comment by lamorrison** [comment]
After examining the code this appears to be because search results for providers with the same name are collapsed into a single result. This prevents the situation where providers who supply many services show up in the result list once for each service. 

In this case it has hidden results for a different provider with the same name. The "Stand Children's Services" results from Auckland are being hidden by the "Stand Children's Services" results from Christchurch - unless an additional term like Auckland is added to the search to exclude the Christchurch results.

An appropriate solution would be to make sure that results are only collapsed together  when the providers share the same name and address.

**Comment by CharlotteHinton** [comment]
@sarahneeson @choirboy07 ready for you to review

**Comment by choirboy07** [comment]
The Auckland provider is now appearing in the results, however there are some results that are not in the order i would expect - see attached.
[Uploading Card 216 Stand Children Services missing.docx...]
