### ISSUE TITLE
Keyword search unexpectedly gives fewer results than category search (example Citizens Advice Bureau)

### ISSUE THREAD

**Issue by sarahneeson** [ServiceInnovationLab/FSD#230]
(Related to [Paul's question in Slack](https://labplus-team.slack.com/archives/CEWNEUCB0/p1553741313004700?thread_ts=1553554720.032200&cid=CEWNEUCB0))

If you search the category [Legal/Civil Services](https://serviceinnovationlab.github.io/FSD/#/FSD/?category=Legal%20%2F%20Civil%20Services), there are 47 results returned for branches of the Citizens Advice Bureau.

Compare that to:

If you search Topic or organisation for the string [Citizens Advice Bureau](https://serviceinnovationlab.github.io/FSD/#/FSD/?keyword=Citizens%20Advice%20Bureau&radius=25), there are 14 results returned for branches of the Citizens Advice Bureau.

I would have expected that a keyword search using that string would return _at least_ the maximum results permitted (50).

Note, when I search the Family Services Directory on the string "citizens advice bureau", there are [92 results](https://www.familyservices.govt.nz/directory/searchresultspublic.htm?searchTerms=%22citizens+advice+bureau%22&cat1=-1&searchRegion=-1&search=Search).

**Is there a reason for this?**

**Comment by dlouise64** [comment]
@lamorrison @JacOng17 @CharlotteHinton #185 is waiting for dev review. It's possible that pull request could fix this. If someone could test this too thanks :)

**Comment by sarahneeson** [comment]
I have retested this issue, and I'm now getting comparable results in both searches (ie. category Legal/Civil Services and keyword Citizens Advice Bureau).  I'm not able to move this issue to Accepted or Closed as I don't yet have rights in Github Projects, but happy for someone else to do this on our behalf.
