### ISSUE TITLE
AddressFinder uses Demo key

### ISSUE THREAD

**Issue by lamorrison** [ServiceInnovationLab/FSD#235]
The AddressFinder API we use for address suggestions is configured using a demo API key. This causes it to show suggestions labelled "DEMO KEY - replace with your own AddressFinder key"

**Comment by lamorrison** [comment]
I've talked to Brenda and there is budget approval for a license key, but it will be tied to the domain name where the production version is deployed.

**Comment by CharlotteHinton** [comment]
@Br3nda @lamorrison how can we move forward with this to move it out of blocked?

**Comment by lamorrison** [comment]
Now that we have publication to the live domain set up and the API key is in an environment variable, we should be able to put the real production API key into the CircleCI config yml
