### ISSUE TITLE
Show map home pin

### ISSUE THREAD

**Issue by Br3nda** [ServiceInnovationLab/FSD#269]
When searching for street address, there isn’t a pin on the map to show that address.
Is okay if you are using a known address (eg. your own address), not too hard to figure out where that is on a map.
But if helping another person, and you can’t visually identify the starting address on the map, how do you know which pins are closest?

**Comment by lamorrison** [comment]
Released to UAT

Adds a home pin (marked H) to the map if a user address has been provided.
* Adds standard and hi-res home map marker .png images (developer art)
* Map centres on user location if available

**Comment by lamorrison** [comment]
While working on the home pin I found out how to set different zoom levels on the map. It would be a smallish task to set a more appropriate zoom level when searching within a region

**Comment by sarahneeson** [comment]
@lamorrison seriously?!  A more zoomed in level would be amazing!

Anyways, cheers to you and @Br3nda, we've had a look at the H home pin, and it's great :)

![Home Pin](https://user-images.githubusercontent.com/34259860/58850436-a3c77700-86e2-11e9-97ef-2f68aa631109.jpg)
