### ISSUE TITLE
Directions function issue

### ISSUE THREAD

**Issue by Br3nda** [ServiceInnovationLab/FSD#270]
iPhone XR

To replicate:

Load search page: family.services.govt.nz
Invoke a search with a street address (eg 1 Viewmont Drive, Harbourview, Lower Hutt)
Select “Directions” link in one of the results

Expected result:
Maps program opens, displaying starting address as a string, and provider’s address as a second string.

Actual result:
Maps program opens, displaying starting address as a pair of latitude, longitude coordinates, and providers’ address as a pair of latitude, longitude coordinates

**Comment by lamorrison** [comment]
Released to UAT.

Uses addresses to generate map directions rather than lat/long
* userAddress is now passed through to more components, and to the service page

This has been tested on desktop, should also work on iPhone but that hasn't been confirmed yet

**Comment by sarahneeson** [comment]
Cheers @lamorrison and @Br3nda!  Paul and I tested this on our respective phones this afternoon.  The address that shows up in the Get Directions appears in its full state immediately, but then appears to truncate to a shortened version.

Immediate display:
![Immediate display](https://user-images.githubusercontent.com/34259860/58850229-a83f6000-86e1-11e9-8bcf-a9b970b11ba7.jpg)
Truncated display:
![Updated display](https://user-images.githubusercontent.com/34259860/58850235-b42b2200-86e1-11e9-89fb-1ebc4e9cf6cd.jpg)

_However_ this is a huge improvement over the addresses appearing as latitude/longitude values for iPhone, so reckon this is fine.  

@choirboy07 - feel free to comment further

**Comment by choirboy07** [comment]
Agree, it's a great improvement - the truncation is now a "nuisance factor" - if it is an easy fix to keep the full address that would be good.
