### ISSUE TITLE
Changes to header and footer

### ISSUE THREAD

**Issue by sarahneeson** [ServiceInnovationLab/FSD#302]
Need to:
- refine commentary in header
- update footer to reflect site being released as Beta

Header (current)
![FWS header](https://user-images.githubusercontent.com/34259860/59005775-e1f3a080-8872-11e9-993e-862c3cc220e2.PNG)

Proposed header text:
This is the mobile responsive site for the Ministry of Social Development’s **Family Services Directory**.  Use the site to look for services near you.

Footer (current)
![FWS footer](https://user-images.githubusercontent.com/34259860/59005835-254e0f00-8873-11e9-95fc-36a2ae84f1a6.PNG)

Proposed footer links:
**About this site** - links to blog about collaboration (TBC)
Send us your **feedback** - links to email address (with pre-populated subject)
Data sourced from **data.govt.nz** 
**Apply to list** on the Family Services Directory - links to application form

**Comment by sarahneeson** [comment]
@Br3nda - a starter for ten from @choirboy07  and @sarahneeson 

Thoughts/comments?

**Comment by Br3nda** [comment]
@sarahneeson looks good and this task is ready for the dev. Should have someone this week.
