### ISSUE TITLE
Order by relevance

### ISSUE THREAD

**Issue by dlouise64** [ServiceInnovationLab/FSD#47]
e.g. a search for "age concern" should show those with both words next to each other first.

"needs more info"

**Comment by Br3nda** [comment]
@camfindlay Do you have a way to convince data.govt.nz to do this for us?

**Comment by CharlotteHinton** [comment]
@Br3nda to follow up with Cam again

**Comment by camfindlay** [comment]
@CharlotteHinton @Br3nda data.govt.nz is just CKAN, suggest picking through it's API docs to determine if it can be done or if there is some way to order by relevant on returned results (or if it cant they might be open to an open source contribution...) See https://docs.ckan.org/en/2.7/api/index.html

**Comment by camfindlay** [comment]
You'll also want to look at the DataStore API which is the bit that allows querying the data itself https://docs.ckan.org/en/2.7/maintaining/datastore.html#the-datastore-api
