### ISSUE TITLE
Multiple services in provider, use accordian

### ISSUE THREAD

**Issue by Br3nda** [ServiceInnovationLab/FSD#69]
If > 1 service on a provider, use an acordian style display to present them

**Comment by Br3nda** [comment]
Should the accordians all be closed at the start or viewing a service?

**Comment by mischa-s** [comment]
Questions: 
- [ ] What to do about multiple services with same SERVICE_NAME (e.g. Connecting Communities Wairarapa, School Holiday Programme – Activity Based)
- [ ] Results for different provider (e.g. Connecting Communities Wairarapa)

**Comment by sarahneeson** [comment]
@Br3nda :  current FSD behaviour with accordions is to have all closed.  

The exception is if the provider only has 1 service, in which case it's expanded by default.  Assuming this presents well in mobile view, could be worth going with that?

@mischa-s : are you getting multiple services with the same name for the provider called Connecting Communities Wairarapa?
Not sure why that is happening - from what I can see, all this provider's services have unique names (see attached)

![Connecting Communities Wairarapa.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a2613c599d956001145c2b3/125516c66e82c728ace21e0d46cb9b942d8780bd86e7b8038752fd993c482e672001b06b4784ea3abe507a110e4d52be011a001ea9aacd39aca439238b5408bfd93e0927c33f19fab88219ed52ba29831d84a4a0980e91b6697abad2c51a7c0c0f0a88f75734a59d42c05df043e54554a01b242e.PNG)
